### PR TITLE
Release 2.0.0

### LINKED ISSUE #1: Support for relationships
See Populate: http://mongoosejs.com/docs/populate.html 
Another example: http://stackoverflow.com/a/11920421/2578205

### LINKED ISSUE #2: Validation
See http://mongoosejs.com/docs/validation.html

### LINKED ISSUE #15: Update examples for 1.0.0 and add example for extension
I think some of the examples need to be updated to get ready for version 1.0.0 and an example for extending a Mongoose service with hooks (I [added one to feathers-mongodb](https://github.com/feathersjs/feathers-mongodb/blob/master/README.md)) would be nice.

### LINKED ISSUE #17: Should use underscores to donate filter params vs. params that are on a model

### PR DESCRIPTION
**Pull request by ekryski**
This PR does a ton:

- makes this adapter consistent with the others in terms of documentation and file structure. (Closes #15 and #12)
- makes this adapter compatible with Feathers 1.x
- updates mongoose dependency to 4.1.0
- adds support for special query filters (Closes #17)
    - $sort
    - $select
    - $skip
    - $limit
    - $populate (Closes #1)
- adds comprehensive tests
- makes connection autoreconnect by default when not passing a connection string
- adds support for mongoose plugins, virtuals, statics, indexes, and methods.
- adds support for validation and ensures validation errors are normalized properly. (Closes #2 and #6)

### CODE REVIEW

**Comment by ekryski** [comment]
Still wrapping up the tests. Then just going to squash the commits and then this should be good to go!

**Comment by marshallswain** [comment]
This is a great release.  @ekryski can you ping me when it's done.  I'm going to deprecate my feathers-mongoose-advanced library.

**Comment by ekryski** [comment]
Just waiting for @Glavin001 to give me publishing credentials on npm so that I can publish this baby.

**Comment by daffl** [comment]
Nice work!

**Comment by Glavin001** [comment]
@ekryski and @daffl should now also be owners of feathers-mongoose.
Thanks for the great work!

**Comment by ekryski** [comment]
ok published! :boom: Thanks @Glavin001

**Comment by marshallswain** [comment]
Cool!

**Pull request merged**
