### PR TITLE
Fix named export 'Service' to export the constructor function

### LINKED ISSUE #37: Named export 'service' should expose constructor function, not init function
In order to be consistent with the documentation here: 
https://github.com/feathersjs/feathers-mongoose#classes-es6

> The module also exports a Babel transpiled ES6 class as Service that can be directly extended like this:

>```
>import Todo from './models/todo';
>import { Service } from 'feathers-sequelize';
>
>class MyService extends Service {
>  create(data, params) {
>    data.user_id = params.user.id;
>
>    return super.create(data, params);
>  }
>}
>```

The named export `service` needs to be the constructor function, not the exported default `init()` function, and also should be called `Service` _captial S_ by convention and to match the documentation.

**Currently:** it exports the same function as the default export, and init function and is *named* **service** _(with a lowercase s)_

```
import * as hooks from './hooks';
import service from './service';

Object.assign(service, { hooks, service });

export default service;
```
https://github.com/feathersjs/feathers-mongoose/blob/master/src/index.js#L4

### PR DESCRIPTION
**Pull request by BigAB**
Fixes #37

### CODE REVIEW

**Comment by ekryski** [comment]
I think this changes the behaviour whereby you'd now always need to call `mongooseService()` with the `new` keyword. I wrote some tests and verified that v3.0.1 supports `import { Service } from 'feathers-mongoose'` which will return the constructor.

If you just `import mongooseService from 'feathers-service'` then "mongooseService" will be the `init` function so that you can just call without the `new` keyword.

**Comment by ekryski** [comment]
I'm going to close this because I don't want to change behaviour and I've now written tests to verify that it is working in v3.0.1+.

**Comment by BigAB** [comment]
It wouldn't change the default behaviour of
```javascript
import mongooseService from 'feathers-service';
mongooseService('/thing', { Model: Thing });
```
..but it would change what I thought was a mistake:
```javascript
import mongooseService from 'feathers-service';
mongooseService.service('/thing', { Model: Thing });
```
... to error.

**Comment by ekryski** [comment]
Right. Let's keep it the way it is for now (even if it is a bit confusing). Thanks for the PR though! :smile:

**Pull request closed without merging**
