### PR TITLE
Ensure bulk create returns plain objects when lean is 'true'

### LINKED ISSUE #161: Make sure create many works with lean:true.  Follow up on #160
Follow up work after https://github.com/feathersjs/feathers-mongoose/pull/160

We need to make sure create is returning the correct type of object whether lean is on or off.  @daffl ran into an issue with this.

### PR DESCRIPTION
**Pull request by DesignByOnyx**
### Summary

This closes #161 

The tests for this are coming in a [separate PR in feathers-service-tests](https://github.com/feathersjs/feathers-service-tests/pull/39).

### CODE REVIEW

**Comment by DesignByOnyx** [comment]
This test is not failing for me locally. I did a fresh npm install and everything passes. Please advise.

**Comment by ekryski** [comment]
@DesignByOnyx which version of Node are you running. It's failing on Node v7.9.0 when checking the ORM error.

```
Uncaught TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at ValidationError.toString (node_modules/mongoose/lib/error/validation.js:49:10)
      at Function.prepareStackTrace (node_modules/source-map-support/source-map-support.js:365:16)
      at Function.captureStackTrace (<anonymous>)
      at new MongooseError (node_modules/mongoose/lib/error.js:12:11)
      at ValidationError (node_modules/mongoose/lib/error/validation.js:17:19)
      at model.Document.invalidate (node_modules/mongoose/lib/document.js:1458:32)
      at node_modules/mongoose/lib/document.js:1334:17
      at validate (node_modules/mongoose/lib/schematype.js:705:7)
      at node_modules/mongoose/lib/schematype.js:742:9
      at Array.forEach (native)
      at SchemaString.SchemaType.doValidate (node_modules/mongoose/lib/schematype.js:710:19)
      at node_modules/mongoose/lib/document.js:1332:9
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

I'll see if I can reproduce locally.

**Comment by DesignByOnyx** [comment]
I tested against Node v7.9.0 before posting my last comment. The test that is failing is a rather simple test, so this really boggles me.

**It's worth noting that this is a "new" test - the test was written a long time ago but wasn't actually being executed prior to this PR.**

After further investigation, there's a slightly different implementation of how errors are emitted between feathers-sequelize and feathers-mongoose. This is best explained by looking at code:

https://github.com/feathersjs/feathers-sequelize/blob/master/src/utils.js#L32
https://github.com/feathersjs/feathers-mongoose/blob/master/src/error-handler.js#L44

Hit me up in Slack so we can talk about this.

**Comment by daffl** [comment]
Merging with latest and re-running fixed it. Released as v5.1.2, thank you!

**Pull request merged**
