### PR TITLE
set travis notifications to slack

### PR DESCRIPTION
**Pull request by ekryski**

### CODE REVIEW

**Comment by daffl** [comment]
Could someone steal that token and spam our Slack?

**Comment by ekryski** [comment]
@daffl technically yes. It's semi-secret. Travis recommends encrypting it using their CLI but it looked like a pain to get up and running and at the time I was feeling lazy, but we should probably be doing that so that we don't knowingly introduce tech debt.

**Comment by ekryski** [comment]
This is what we are supposed to do. https://docs.travis-ci.com/user/notifications#Slack-notifications

**Comment by ekryski** [comment]
Talked with @corymsmith and looks like he has scripted a bunch of this and also encrypted it. @corymsmith maybe it makes sense to just close this PR?

**Comment by corymsmith** [comment]
Yes, will close this now as its covered by my other changes.

**Pull request closed without merging**
