### PR TITLE
making lean true by default. Breaking change. Closes #132

### LINKED ISSUE #132: Make lean: true by default
Lots of discussion in #110 but basically lean:true doesn't seem to have many drawbacks. It is faster and then people don't have to do the weird `toObject` everywhere.

### PR DESCRIPTION
**Pull request by ekryski**
- [ ] Need to include documentation on virtuals when using this option.

### CODE REVIEW

**Comment by daffl** [comment]
I'd like to get #124 in first and make a 3.6 then we can make a 4.0 with this?

**Comment by ekryski** [comment]
@daffl definitely this should wait until #124, #133 and #134 are merged. Just thought I would put this together since I was already in the code.

**Comment by theonlyelf** [comment]
It looks like everything is ready for this aside from the conflicting files in `test/index.text.js`.

How can add commits to this PR to fix the conflict (or would I have to create a separate PR)?

**Comment by daffl** [comment]
I submitted a new PR with the change. Released now as 4.0.0

**Pull request closed without merging**
