### PR TITLE
Added warning msg when options.lean is falsey

### PR DESCRIPTION
**Pull request by eddyystop**
- [ ] Tell us about the problem your pull request is solving.

People are told on #help they have to configure Mongoose with { lean: true } with some frequency. Hours are lost on this problem. See #help jojobyte posting first Dec 18  2:42am and finding an answer 7:26pm.

Supposedly { lean: true } is either not in or not prominent in the docs. Displaying a console message might help even when people don't read the docs.

- [ ] Are there any open issues that are related to this?

No.

- [ ] Is this PR dependent on PRs in other repos?

Yes.

### Other Information

I believe Sequelize has a similar issue. I assume I can made a similar PR for it.

### CODE REVIEW

**Comment by eddyystop** [comment]
master branch has Travis errors as well.

**Comment by marshallswain** [comment]
:shipit:

**Comment by daffl** [comment]
I'd still like to figure out a good way to send deprecation warnings. Plain `console.log` without an option to disable them makes production app logs pretty noisy.

**Comment by eddyystop** [comment]
This msg is suppressed in production mode.

**Pull request merged**
