### PR TITLE
Add feathers-hooks compatibility.

### PR DESCRIPTION
**Pull request by marshallswain**
This lets you define hooks directly in the entity object:

```js
var authHooks = require('feathers-authentication').hooks;

var Property = {
  schema: {
    title: {type: String, required: true},
    description: {type: String},
    sold: {type: Boolean, 'default': false}
  },
  methods: {
    isComplete: function(){
      return this.complete;
    }
  },
  statics: {
  },
  virtuals: {
    'id': function(){
      return this._id.toHexString();
    }
  },
  indexes: [
  ],
  // Hooks
  before:{
    // These are just examples.  You are responsible to secure your own data.
    all: [authHooks.requireAuth],
    find: [authHooks.queryWithUserId],
    get: [authHooks.queryWithUserId],
    create: [authHooks.setUserId],
    update: [authHooks.setUserId],
    patch: [authHooks.setUserId],
    remove: [authHooks.setUserId]
  },
  after:{
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};

module.exports = Property;
```

### CODE REVIEW

**Comment by marshallswain** [comment]
@ekryski I've run the tests locally and they pass when running a local mongod.  I updated the test to show that adding before and after keys to the object does not interfere with the existing tests, but I'm not firing up a server to test the hooks.

What do you think?  Can we merge?

screen shot 2015-10-03 at 4 50 30 am

**Comment by marshallswain** [comment]
@daffl @ekryski Can somebody please comment on this?

**Comment by ekryski** [comment]
@marshallswain Sorry for the delay mate. This kind of slipped passed me in my email. Thanks for pinging again!

My first thought was this makes things a bit more inconsistent with the other database adapters, **but** I think in this case that's ok. The mongoose adapter is a bit special. It works fine on my end so :shipit:. 

Could you add some documentation to the readme about how to use them? I think you can just drop in your example.

To avoid confusion I think we should also highlight the difference between mongoose [middleware](http://mongoosejs.com/docs/middleware.html) and our hooks. A quick stab might be:

_Feathers hooks are just middleware that are applied at the service level and give you more fine grained control over when each hook is applied by allowing you to specify which CRUD method will trigger them, as opposed to just being called on all saves or updates. With that said, both can be used in conjunction._

**Comment by marshallswain** [comment]
@daffl or @ekryski I've added the docs.  Can one of you publish this?  Or add me to the npm package?

**Comment by daffl** [comment]
I've added you on NPM. Does this also address #25? If not we might want to add that as well before publishing. Side note: This plugin probably needs to be updated to the new structure, too.

**Comment by marshallswain** [comment]
This doesn't fully address #25.

**Pull request merged**
