### PR TITLE
Ensure we convert mongoose models to regular objects. Closes #110.

### LINKED ISSUE #110: patch doesn't throw correct object
Using auth for facebook generated by feathers cli, patch function fails , the issue is with the data parameter in service.js on line 164.

For more verbose explanation 

```
  feathers-authentication:oauth2 Updating user: 57b71962784bec9f311e4462 +821ms
  feathers:rest Error in REST handler: `Invalid atomic update value for $__original_remo
ve. Expected an object, received function` +11ms
  feathers-authentication:middleware An authentication error occurred. +2ms Error: Inval
id atomic update value for $__original_remove. Expected an object, received function
    at Query._castUpdate (/home/shriyans/Projects/test-app/node_modules/mongoose/lib/que
ry.js:2378:13)
    at Query.update (/home/shriyans/Projects/test-app/node_modules/mongoose/lib/query.js
:2161:22)
    at Function.update (/home/shriyans/Projects/test-app/node_modules/mongoose/lib/model
.js:2056:13)
    at Object.patch (/home/shriyans/Projects/test-app/node_modules/feathers-mongoose/lib
/service.js:255:27)
  at /home/shriyans/Projects/test-app/node_modules/feathers-hooks/lib/hooks.js:74:31
    at new Promise (/home/shriyans/Projects/test-app/node_modules/core-js/modules/es6.pr
omise.js:191:7)
    at /home/shriyans/Projects/test-app/node_modules/feathers-hooks/lib/hooks.js:58:16
    at run (/home/shriyans/Projects/test-app/node_modules/core-js/modules/es6.promise.js:87:22)
    at /home/shriyans/Projects/test-app/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/home/shriyans/Projects/test-app/node_modules/core-js/modules/_microtask.j
s:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### PR DESCRIPTION
**Pull request by ekryski**

### CODE REVIEW

**Comment by daffl** [comment]
Do we want to do that? This change might have weird side effects for people that are using models (e.g. with getters etc.). We could make a breaking release that sets `lean: true` by default or only calls `toObject` in those methods if `lean: true` (but then it should do `remove` as well).

**Comment by corymsmith** [comment]
I had a similar thought as @daffl, are there implications / side effects to doing this?

**Comment by ekryski** [comment]
@daffl @corymsmith no it's not an issue or at least no worse than what currently happens. Right now, we're not calling save on the `data` object. If this was a mongoose model and we did this that is what would trigger `pre` and `post` mongoose hooks. Since we're not doing that, it's just treated as a normal JS object and mongoose will return a mongoose model after the DB call (unless you're using `lean: true`).

Currently if you pass a mongoose model it just blows up. Hence #110.

**Comment by daffl** [comment]
Oh sorry... I totally read that wrong. All good, :shipit:

**Pull request merged**
